### ISSUE TITLE
Unable to run the example wav file embedded in the code

### ISSUE THREAD

**Issue by harisainathuni** [CatalystCode/SpeechToText-WebSockets-Java#1]
Hi Clemens,

I happened to find your project through github and I want to use bing speech api using websockets from Java. I have already found the JS solution from Microsoft Azure. When I try to run your sample I am getting the following error.
[error] (run-main-0) javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input stream
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input stream
        at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1121)
        at com.github.catalystcode.fortis.speechtotext.SpeechTranscriber.transcribe(SpeechTranscriber.java:36)
        at com.github.catalystcode.fortis.speechtotext.SpeechTranscriber.transcribe(SpeechTranscriber.java:31)
        at SpeechToTextWebsocketsDemo.main(SpeechToTextWebsocketsDemo.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed Jun 1, 2017 4:04:19 PM

Any insight that you can provide to this issue.

**Comment by c-w** [comment]
Hi @harisainathuni. Apologies for the late reply; for some reason I didn't get a notification about this issue.

Which command are you running specifically and what operating system are you using? I've tested the sample code on Java 8 and Windows 10. Here is a sample run log of what happens when I run the `batman.wav` sbt command mentioned in the README: [sbt.log.txt](https://github.com/CatalystCode/SpeechToText-WebSockets-Java/files/1082759/sbt.log.txt)

Looking at the error message, it seems to me like your machine may be missing an audio codec. Were you by chance testing with the `hall.mp3` file and referencing the library via Maven? If that's the case, please make sure to add the tritonious jars ([1](https://github.com/CatalystCode/SpeechToText-WebSockets-Java/raw/master/lib/tritonus_share-0.3.6.jar), [2](https://github.com/CatalystCode/SpeechToText-WebSockets-Java/raw/master/lib/tritonus_remaining-0.3.6.jar)) to your classpath as mentioned in the README as unfortunately the jars are currently not being auto-added.

**Comment by c-w** [comment]
@harisainathuni Given that I wasn't able to reproduce this issue, I'll resolve the ticket for now. If this is still a problem for you, please let me know and feel free to re-open the ticket.
